controller_list:
  - name: arm_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - finger_joint
      - left_inner_finger_joint
      - left_inner_knuckle_joint
      - right_inner_knuckle_joint
      - right_outer_knuckle_joint
      - right_inner_finger_joint
